
var roomsCh1 = [
  {value:315,text:`?????? (Dark World Closet)`},
  {value:320,text:`Eye Puzzle`},
  {value:325,text:`Castle Town`},
  {value:329,text:`Field - Great Door`},
  {value:336,text:`Field - Maze of Death`},
  {value:339,text:`Seam's Shop`},
  {value:348,text:`Field - Great Board`},
  {value:351,text:`Great Board 2`},
  {value:353,text:`Forest - Entrance`},
  {value:362,text:`Forest - Bake Sale`},
  {value:370,text:`Forest - Before Maze`},
  {value:376,text:`Forest - After Maze`},
  {value:377,text:`Forest - Thrashing Room`},
  {value:387,text:`Card Castle - Prison`},
  {value:391,text:`Card Castle - ??? (Basement)`},
  {value:394,text:`Card Castle - 1F`},
  {value:403,text:`Card Castle - 5F`},
  {value:406,text:`Card Castle - Throne`}
];

var rooms = [
  {value:3,text:`Queen's Mansion - Rooftop`},
  {value:71,text:`My Castle Town`},
  {value:84,text:`Dark World`},
  {value:87,text:`Cyber Field Entrance`},
  {value:91,text:`Cyber Field - Arcade Machine`},
  {value:98,text:`Cyber Field - Music Shop`},
  {value:121,text:`Cyber City - Entrance`},
  {value:124,text:`Cyber City - First Alleyway`},
  {value:130,text:`Cyber City - Music Shop`},
  {value:135,text:`Cyber City - Mouse Alley`},
  {value:137,text:`Second Alleyway`},
  {value:142,text:`Cyber City - Heights`},
  {value:161,text:`Queen's Mansion - Mess Hall`},
  {value:166,text:`Queen's Mansion - Entrance`},
  {value:180,text:`Queen's Mansion - Basement`},
  {value:196,text:`Queen's Mansion - 3F`},
  {value:202,text:`Queen's Mansion - Acid Tunnel`},
  {value:205,text:`Queen's Mansion - 4F`},
];

var rooms_all = [
  {value:1,text:`room_intro_ch2`},
{value:2,text:`room_dw_mansion_fountain`},
{value:3,text:`room_dw_mansion_prefountain`},
{value:4,text:`room_debug_choicer_light`},
{value:5,text:`room_debug_smallface`},
{value:6,text:`room_debug_battleBalloon`},
{value:7,text:`room_debug_smallface_dark`},
{value:8,text:`room_debug_choicer_dark`},
{value:9,text:`room_gms_debug_failsafe`},
{value:10,text:`ROOM_INITIALIZE`},
{value:11,text:`room_title_placeholder`},
{value:12,text:`room_battletest`},
{value:13,text:`room_cutscene_tester`},
{value:14,text:`room_sound_tester`},
{value:15,text:`room_sprite_tester`},
{value:16,text:`room_gif_tester`},
{value:17,text:`room_bullettest`},
{value:18,text:`room_teacup_demoauto`},
{value:19,text:`room_teacup_demobullets`},
{value:20,text:`room_shaun_puzzle`},
{value:21,text:`room_GMS2_test`},
{value:22,text:`room_cutscene_tester_b`},
{value:23,text:`room_debug_color`},
{value:24,text:`room_debug_battle`},
{value:25,text:`room_debug_loc`},
{value:26,text:`PLACE_CONTACT`},
{value:27,text:`room_krisroom`},
{value:28,text:`room_krishallway`},
{value:29,text:`room_torroom`},
{value:30,text:`room_torhouse`},
{value:31,text:`room_torbathroom`},
{value:32,text:`room_town_krisyard`},
{value:33,text:`room_town_northwest`},
{value:34,text:`room_town_north`},
{value:35,text:`room_beach`},
{value:36,text:`room_town_mid`},
{value:37,text:`room_town_apartments`},
{value:38,text:`room_town_south`},
{value:39,text:`room_town_school`},
{value:40,text:`room_town_church`},
{value:41,text:`room_graveyard`},
{value:42,text:`room_town_shelter`},
{value:43,text:`room_hospital_lobby`},
{value:44,text:`room_hospital_hallway`},
{value:45,text:`room_hospital_rudy`},
{value:46,text:`room_hospital_room2`},
{value:47,text:`room_diner`},
{value:48,text:`room_townhall`},
{value:49,text:`room_flowershop_1f`},
{value:50,text:`room_flowershop_2f`},
{value:51,text:`room_library`},
{value:52,text:`room_alphysalley`},
{value:53,text:`room_lw_computer_lab`},
{value:54,text:`room_lw_library_upstairs`},
{value:55,text:`room_lw_police`},
{value:56,text:`room_lw_conbini`},
{value:57,text:`room_lw_icee_pizza`},
{value:58,text:`room_torielclass`},
{value:59,text:`room_schoollobby`},
{value:60,text:`room_alphysclass`},
{value:61,text:`room_schooldoor`},
{value:62,text:`room_insidecloset`},
{value:63,text:`room_school_unusedroom`},
{value:64,text:`room_castle_town`},
{value:65,text:`room_castle_tutorial`},
{value:66,text:`room_dw_castle_west_cliff_old`},
{value:67,text:`room_dw_castle_east_door`},
{value:68,text:`room_dw_castle_west_cliff`},
{value:69,text:`room_dw_castle_area_1`},
{value:70,text:`room_dw_castle_area_2`},
{value:71,text:`room_dw_castle_area_2_transformed`},
{value:72,text:`room_dw_ralsei_castle_front`},
{value:73,text:`room_dw_castle_restaurant`},
{value:74,text:`room_dw_castle_cafe`},
{value:75,text:`room_dw_castle_dojo`},
{value:76,text:`room_dw_ralsei_castle_1f`},
{value:77,text:`room_dw_ralsei_castle_2f`},
{value:78,text:`room_dw_castle_dungeon`},
{value:79,text:`room_dw_castle_rooms_hallway`},
{value:80,text:`room_dw_castle_rooms_kris`},
{value:81,text:`room_dw_castle_rooms_susie`},
{value:82,text:`room_dw_castle_rooms_lancer`},
{value:83,text:`room_dw_cyber_intro_1`},
{value:84,text:`room_dw_cyber_intro_connector`},
{value:85,text:`room_dw_cyber_intro_2`},
{value:86,text:`room_dw_cyber_rhythm_slide`},
{value:87,text:`room_dw_cyber_savepoint`},
{value:88,text:`room_dw_cyber_battle_maze_1`},
{value:89,text:`room_dw_cyber_music_bullet`},
{value:90,text:`room_dw_cyber_tasque_battle`},
{value:91,text:`room_dw_cyber_keyboard_puzzle_1`},
{value:92,text:`room_dw_cyber_queen_boxing`},
{value:93,text:`room_dw_cyber_musical_door`},
{value:94,text:`room_dw_cyber_maze_virokun`},
{value:95,text:`room_dw_cyber_keyboard_puzzle_2`},
{value:96,text:`room_dw_cyber_battle_maze_2`},
{value:97,text:`room_dw_cyber_music_final`},
{value:98,text:`room_dw_cyber_musical_shop`},
{value:99,text:`room_dw_cyber_teacup_final`},
{value:100,text:`room_dw_cyber_rollercoaster`},
{value:101,text:`room_dw_cyber_maze_fireworks`},
{value:102,text:`room_dw_cyber_maze_tasque`},
{value:103,text:`room_dw_cyber_maze_queenscreen`},
{value:104,text:`room_dw_cyber_viro_ring`},
{value:105,text:`room_dw_cyber_post_music_boss_slide`},
{value:106,text:`room_dw_cyber_keyboard_puzzle_3`},
{value:107,text:`room_dw_cyber_battle_maze_3`},
{value:108,text:`room_dw_cyber_teacup_2`},
{value:109,text:`room_dw_cyber_shaunsmusicalbullettunnel`},
{value:110,text:`room_dw_cyber_maze_rhythm`},
{value:111,text:`room_dw_cyber_escalator_slide`},
{value:112,text:`room_dw_cyber_nuberts_treasure`},
{value:113,text:`room_dw_cyber_music_fight`},
{value:114,text:`room_dw_cyber_keyboardexample`},
{value:115,text:`room_dw_city_prototype_01`},
{value:116,text:`room_dw_city_prototype_02`},
{value:117,text:`room_dw_city_spamton_shop_exterior`},
{value:118,text:`room_dw_city_spamton_house`},
{value:119,text:`room_dw_city_intro`},
{value:120,text:`room_dw_city_split`},
{value:121,text:`room_dw_city_entrance`},
{value:122,text:`room_dw_city_traffic_1`},
{value:123,text:`room_dw_city_roadblock`},
{value:124,text:`room_dw_city_hacker`},
{value:125,text:`room_dw_city_mice`},
{value:126,text:`room_dw_city_big_1`},
{value:127,text:`room_dw_city_traffic_2`},
{value:128,text:`room_dw_city_big_2`},
{value:129,text:`room_dw_city_queen_drunk`},
{value:130,text:`room_dw_city_savepoint`},
{value:131,text:`room_dw_city_big_3`},
{value:132,text:`room_dw_city_traffic_3`},
{value:133,text:`room_dw_city_mice2`},
{value:134,text:`room_dw_city_cheesemaze`},
{value:135,text:`room_dw_city_mice3`},
{value:136,text:`room_dw_city_poppup`},
{value:137,text:`room_dw_city_berdly`},
{value:138,text:`room_dw_city_traffic_4`},
{value:139,text:`room_dw_city_spamton_alley`},
{value:140,text:`room_dw_city_monologue`},
{value:141,text:`room_dw_city_baseball`},
{value:142,text:`room_dw_city_postbaseball_1`},
{value:143,text:`room_dw_city_postbaseball_2`},
{value:144,text:`room_dw_city_postbaseball_3`},
{value:145,text:`room_dw_city_mansion_front`},
{value:146,text:`room_dw_city_susie_ralsei_fun_1`},
{value:147,text:`room_dw_city_mirrorfriend`},
{value:148,text:`room_dw_city_treasure`},
{value:149,text:`room_dw_city_dog_traffic`},
{value:150,text:`room_dw_city_man`},
{value:151,text:`room_dw_city_moss`},
{value:152,text:`room_dw_city_big_3_backup_2exits`},
{value:153,text:`room_dw_city_traffic_3_2Entrances`},
{value:154,text:`room_dw_city_cheese`},
{value:155,text:`room_dw_city_carnival`},
{value:156,text:`room_dw_city_noelle_fight_intro`},
{value:157,text:`room_dw_city_spamton_shop_interior`},
{value:158,text:`room_dw_city_monologue_old`},
{value:159,text:`room_dw_mansion_krisroom`},
{value:160,text:`room_dw_mansion_susieroom`},
{value:161,text:`room_dw_mansion_lightner_hallway`},
{value:162,text:`room_dw_mansion_darkbulb_1`},
{value:163,text:`room_dw_mansion_darkbulb_2`},
{value:164,text:`room_dw_mansion_darkbulb_3`},
{value:165,text:`room_dw_mansion_dining_a`},
{value:166,text:`room_dw_mansion_entrance`},
{value:167,text:`room_dw_mansion_fire_paintings`},
{value:168,text:`room_dw_mansion_single_pot`},
{value:169,text:`room_dw_mansion_potBalance`},
{value:170,text:`room_dw_mansion_tasquePaintings`},
{value:171,text:`room_dw_mansion_traffic`},
{value:172,text:`room_dw_mansion_east_1f_e`},
{value:173,text:`room_dw_mansion_east_1f_secret`},
{value:174,text:`room_dw_mansion_east_teacup`},
{value:175,text:`room_dw_mansion_east_teacup_4`},
{value:176,text:`room_dw_mansion_east_teacup_3`},
{value:177,text:`room_dw_mansion_east_teacup_2`},
{value:178,text:`room_dw_mansion_b_entrance`},
{value:179,text:`room_dw_mansion_b_stairs`},
{value:180,text:`room_dw_mansion_b_central`},
{value:181,text:`room_dw_mansion_b_west_1f`},
{value:182,text:`room_dw_mansion_b_west_1f_a`},
{value:183,text:`room_dw_mansion_b_west_1f_b`},
{value:184,text:`room_dw_mansion_b_west_2f`},
{value:185,text:`room_dw_mansion_b_east`},
{value:186,text:`room_dw_mansion_b_east_a`},
{value:187,text:`room_dw_mansion_b_east_b`},
{value:188,text:`room_dw_mansion_b_east_transformed`},
{value:189,text:`room_dw_mansion_east_2f_a`},
{value:190,text:`room_dw_mansion_east_2f_transformed_new`},
{value:191,text:`room_dw_mansion_east_2f_shortcut`},
{value:192,text:`room_dw_mansion_kitchen`},
{value:193,text:`room_dw_mansion_east_2f_c`},
{value:194,text:`room_dw_mansion_east_2f_c_a`},
{value:195,text:`room_dw_mansion_east_2f_d`},
{value:196,text:`room_dw_mansion_east_3f`},
{value:197,text:`room_dw_mansion_east_3f_projection`},
{value:198,text:`room_dw_mansion_east_3f_toilet`},
{value:199,text:`room_dw_mansion_acid_tunnel`},
{value:200,text:`room_dw_mansion_acid_tunnel_puzzle_entrance`},
{value:201,text:`room_dw_mansion_acid_tunnel_loop_rouxls`},
{value:202,text:`room_dw_mansion_acid_tunnel_exit`},
{value:203,text:`room_dw_mansion_east_4f_b`},
{value:204,text:`room_dw_mansion_east_4f_c`},
{value:205,text:`room_dw_mansion_east_4f_d`},
{value:206,text:`room_dw_mansion_top`},
{value:207,text:`room_dw_mansion_top_post`},
{value:208,text:`room_dw_mansion_ferris_wheel`},
{value:209,text:`room_dw_mansion_ferris_wheel_post`},
{value:210,text:`room_dw_mansion_noelle_room`},
{value:211,text:`room_dw_mansion_bridges`},
{value:212,text:`room_dw_mansion_bridges_funny`},
{value:213,text:`room_dw_mansion_mouseLottery`},
{value:214,text:`room_dw_mansion_hands`},
{value:215,text:`room_dw_mansion_dining3`},
{value:216,text:`room_dw_mansion_dininghall`},
{value:217,text:`room_dw_mansion_dining_storage`},
{value:218,text:`room_dw_mansion_east_1f_b`},
{value:219,text:`room_dw_mansion_east_2f_c_b`},
{value:220,text:`room_dw_mansion_traffic_original`},
{value:221,text:`room_dw_mansion_east_1f_a`},
{value:222,text:`room_dw_mansion_east_2f_teacup`},
{value:223,text:`room_dw_mansion_east_4f_e`},
{value:224,text:`room_dw_mansion_east_4f_a`},
{value:225,text:`room_dw_mansion_east_2f_ufo_old`},
{value:226,text:`room_dw_mansion_east_1f_d`},
{value:227,text:`room_dw_mansion_east_1f_c`},
{value:228,text:`room_dw_mansion_sparks`},
{value:229,text:`room_dw_mansion_acid_tunnel_old`},
{value:230,text:`room_dw_mansion_top_post_old`},
{value:231,text:`room_dw_mansion_elevator`},
{value:232,text:`PLACE_DOG`},
{value:233,text:`room_legend`},
{value:234,text:`room_legend_neo`},
{value:235,text:`room_shop1`},
{value:236,text:`room_shop_ch2_music`},
{value:237,text:`room_shop_ch2_swatch`},
{value:238,text:`room_shop_ch2_spamton`},
{value:239,text:`room_gameover`},
{value:240,text:`PLACE_LOGO`},
{value:241,text:`PLACE_FAILURE`},
{value:242,text:`PLACE_NAMING_JIKKEN`},
{value:243,text:`PLACE_MENU`},
{value:244,text:`room_ed`},
{value:245,text:`room_empty`},
{value:246,text:`room_DARKempty`},
{value:247,text:`room_DARKbase_GMS2`},
{value:248,text:`room_dw_cyber_battle_maze_2_old`},
{value:249,text:`room_dw_cyber_keyboard_puzzle_1_old`},
{value:250,text:`room_dw_cyber_tasque_battle_og`},
{value:251,text:`room_dw_cyber_savepoint_original`},
{value:252,text:`room_dw_cyber_battle_maze_1_Original`},
{value:253,text:`room_dw_cyber_music_bullet_original`},
{value:254,text:`room_dw_cyber_maze_virokun_backuo`},
{value:255,text:`room_dw_cyber_battle_maze_2_toby`},
{value:256,text:`room_dw_city_big_1_original`},
{value:257,text:`room_dw_city_traffic_2_old`},
{value:258,text:`room_dw_city_big_2_OG`},
{value:259,text:`room_dw_city_mice2_og`},
{value:260,text:`room_dw_mansion_east_teacup_4_old`},
{value:261,text:`room_dw_cyber_teacup_1`},
{value:262,text:`room_dw_cyber_viromaze2`},
{value:263,text:`room_dw_city_traffic_5_old`},
{value:264,text:`room_dw_mansion_dining_storage_old`},
{value:265,text:`room_dw_cyber_virovirokun_fight`},
{value:266,text:`room_dw_mansion_east_2f_d_backup`},
{value:267,text:`room_dw_city_traffic_3_backup`},
{value:268,text:`room_cc_lancer`},
{value:269,text:`room_cc_clover`},
{value:270,text:`room_cc_fountain`},
{value:271,text:`room_dw_city_big_3_og`},
{value:272,text:`room_dw_mansion_bridgesold`},
{value:273,text:`room_dw_city_sidewayscars`},
{value:274,text:`room_transformation_sequence`},
{value:275,text:`room_dw_mansion_gigaqueen`},
{value:276,text:`room_musical_sync_test`},
{value:277,text:`room_chapter_continue_ch1`},
{value:278,text:`PLACE_CHAPTER_SELECT_2x`},
{value:279,text:`PLACE_CHAPTER_SELECT`},
{value:280,text:`ROOM_INITIALIZE_ch1`},
{value:281,text:`PLACE_CONTACT_ch1`},
{value:282,text:`room_krisroom_ch1`},
{value:283,text:`room_krishallway_ch1`},
{value:284,text:`room_torroom_ch1`},
{value:285,text:`room_torhouse_ch1`},
{value:286,text:`room_torbathroom_ch1`},
{value:287,text:`room_town_krisyard_ch1`},
{value:288,text:`room_town_northwest_ch1`},
{value:289,text:`room_town_north_ch1`},
{value:290,text:`room_beach_ch1`},
{value:291,text:`room_town_mid_ch1`},
{value:292,text:`room_town_apartments_ch1`},
{value:293,text:`room_town_south_ch1`},
{value:294,text:`room_town_school_ch1`},
{value:295,text:`room_town_church_ch1`},
{value:296,text:`room_graveyard_ch1`},
{value:297,text:`room_town_shelter_ch1`},
{value:298,text:`room_hospital_lobby_ch1`},
{value:299,text:`room_hospital_hallway_ch1`},
{value:300,text:`room_hospital_rudy_ch1`},
{value:301,text:`room_hospital_room2_ch1`},
{value:302,text:`room_diner_ch1`},
{value:303,text:`room_townhall_ch1`},
{value:304,text:`room_flowershop_1f_ch1`},
{value:305,text:`room_flowershop_2f_ch1`},
{value:306,text:`room_library_ch1`},
{value:307,text:`room_alphysalley_ch1`},
{value:308,text:`room_torielclass_ch1`},
{value:309,text:`room_schoollobby_ch1`},
{value:310,text:`room_alphysclass_ch1`},
{value:311,text:`room_schooldoor_ch1`},
{value:312,text:`room_insidecloset_ch1`},
{value:313,text:`room_school_unusedroom_ch1`},
{value:314,text:`room_dark1_ch1`},
{value:315,text:`room_dark1a_ch1`},
{value:316,text:`room_dark2_ch1`},
{value:317,text:`room_dark3_ch1`},
{value:318,text:`room_dark3a_ch1`},
{value:319,text:`room_dark_wobbles_ch1`},
{value:320,text:`room_dark_eyepuzzle_ch1`},
{value:321,text:`room_dark7_ch1`},
{value:322,text:`room_dark_chase1_ch1`},
{value:323,text:`room_dark_chase2_ch1`},
{value:324,text:`room_castle_outskirts_ch1`},
{value:325,text:`room_castle_town_ch1`},
{value:326,text:`room_castle_front_ch1`},
{value:327,text:`room_castle_tutorial_ch1`},
{value:328,text:`room_castle_darkdoor_ch1`},
{value:329,text:`room_field_start_ch1`},
{value:330,text:`room_field_forest_ch1`},
{value:331,text:`room_field1_ch1`},
{value:332,text:`room_field2_ch1`},
{value:333,text:`room_field2A_ch1`},
{value:334,text:`room_field_topchef_ch1`},
{value:335,text:`room_field_puzzle1_ch1`},
{value:336,text:`room_field_maze_ch1`},
{value:337,text:`room_field_puzzle2_ch1`},
{value:338,text:`room_field_getsusie_ch1`},
{value:339,text:`room_field_shop1_ch1`},
{value:340,text:`room_field_puzzletutorial_ch1`},
{value:341,text:`room_field3_ch1`},
{value:342,text:`room_field_boxpuzzle_ch1`},
{value:343,text:`room_field4_ch1`},
{value:344,text:`room_field_secret1_ch1`},
{value:345,text:`room_field_checkers4_ch1`},
{value:346,text:`room_field_checkers2_ch1`},
{value:347,text:`room_field_checkers6_ch1`},
{value:348,text:`room_field_checkers3_ch1`},
{value:349,text:`room_field_checkers1_ch1`},
{value:350,text:`room_field_checkers5_ch1`},
{value:351,text:`room_field_checkers7_ch1`},
{value:352,text:`room_field_checkersboss_ch1`},
{value:353,text:`room_forest_savepoint1_ch1`},
{value:354,text:`room_forest_area0_ch1`},
{value:355,text:`room_forest_area1_ch1`},
{value:356,text:`room_forest_area2_ch1`},
{value:357,text:`room_forest_area2A_ch1`},
{value:358,text:`room_forest_puzzle1_ch1`},
{value:359,text:`room_forest_beforeclover_ch1`},
{value:360,text:`room_forest_area3A_ch1`},
{value:361,text:`room_forest_area3_ch1`},
{value:362,text:`room_forest_savepoint2_ch1`},
{value:363,text:`room_forest_smith_ch1`},
{value:364,text:`room_forest_area4_ch1`},
{value:365,text:`room_forest_dancers1_ch1`},
{value:366,text:`room_forest_secret1_ch1`},
{value:367,text:`room_forest_thrashmaker_ch1`},
{value:368,text:`room_forest_starwalker_ch1`},
{value:369,text:`room_forest_area5_ch1`},
{value:370,text:`room_forest_savepoint_relax_ch1`},
{value:371,text:`room_forest_maze1_ch1`},
{value:372,text:`room_forest_maze_deadend_ch1`},
{value:373,text:`room_forest_maze_susie_ch1`},
{value:374,text:`room_forest_maze2_ch1`},
{value:375,text:`room_forest_maze_deadend2_ch1`},
{value:376,text:`room_forest_savepoint3_ch1`},
{value:377,text:`room_forest_fightsusie_ch1`},
{value:378,text:`room_forest_afterthrash2_ch1`},
{value:379,text:`room_forest_afterthrash3_ch1`},
{value:380,text:`room_forest_afterthrash4_ch1`},
{value:381,text:`room_forest_castleview_ch1`},
{value:382,text:`room_forest_chase1_ch1`},
{value:383,text:`room_forest_chase2_ch1`},
{value:384,text:`room_forest_castlefront_ch1`},
{value:385,text:`room_cc_prison_cells_ch1`},
{value:386,text:`room_cc_prisonlancer_ch1`},
{value:387,text:`room_cc_prison_to_elevator_ch1`},
{value:388,text:`room_cc_prison2_ch1`},
{value:389,text:`room_cc_prisonelevator_ch1`},
{value:390,text:`room_cc_elevator_ch1`},
{value:391,text:`room_cc_prison_prejoker_ch1`},
{value:392,text:`room_cc_joker_ch1`},
{value:393,text:`room_cc_entrance_ch1`},
{value:394,text:`room_cc_1f_ch1`},
{value:395,text:`room_cc_rudinn_ch1`},
{value:396,text:`room_cc_2f_ch1`},
{value:397,text:`room_cc_rurus1_ch1`},
{value:398,text:`room_cc_3f_ch1`},
{value:399,text:`room_cc_hathy_ch1`},
{value:400,text:`room_cc_4f_ch1`},
{value:401,text:`room_cc_rurus2_ch1`},
{value:402,text:`room_cc_clover_ch1`},
{value:403,text:`room_cc_5f_ch1`},
{value:404,text:`room_cc_lancer_ch1`},
{value:405,text:`room_cc_6f_ch1`},
{value:406,text:`room_cc_throneroom_ch1`},
{value:407,text:`room_cc_preroof_ch1`},
{value:408,text:`room_cc_kingbattle_ch1`},
{value:409,text:`room_cc_prefountain_ch1`},
{value:410,text:`room_cc_fountain_ch1`},
{value:411,text:`PLACE_DOG_ch1`},
{value:412,text:`room_legend_ch1`},
{value:413,text:`room_shop1_ch1`},
{value:414,text:`room_shop2_ch1`},
{value:415,text:`room_gameover_ch1`},
{value:416,text:`room_myroom_dark_ch1`},
{value:417,text:`PLACE_LOGO_ch1`},
{value:418,text:`PLACE_FAILURE_ch1`},
{value:419,text:`PLACE_MENU_ch1`},
{value:420,text:`room_ed_ch1`},
{value:421,text:`room_empty_ch1`},
{value:422,text:`room_man_ch1`},
{value:423,text:`room_DARKempty_ch1`},
{value:424,text:`room_battletest_ch1`},
{value:425,text:`room_splashscreen_ch1`}

];


var weaponsCh1 = [
{value:0,text:`(Nothing)`},
{value:1,text:`Wood Blade`},
{value:2,text:`Mane Ax`},
{value:3,text:`Red Scarf`},
{value:4,text:`EverybodyWeapon`},
{value:5,text:`Spookysword`},
{value:6,text:`Brave Ax`},
{value:7,text:`Devilsknife`},
{value:8,text:`Trefoil`},
{value:9,text:`Ragger`},
{value:10,text:`DaintyScarf`}
];

var weapons = [
{value:0,text:`(Nothing)`},
{value:1,text:`Wood Blade`},
{value:2,text:`Mane Ax`},
{value:3,text:`Red Scarf`},
{value:4,text:`EverybodyWeapon`},
{value:5,text:`Spookysword`},
{value:6,text:`Brave Ax`},
{value:7,text:`Devilsknife`},
{value:8,text:`Trefoil`},
{value:9,text:`Ragger`},
{value:10,text:`DaintyScarf`},
{value:11,text:`TwistedSwd`},
{value:12,text:`SnowRing`},
{value:13,text:`ThornRing`},
{value:14,text:`BounceBlade`},
{value:15,text:`CheerScarf`},
{value:16,text:`MechaSaber`},
{value:17,text:`AutoAxe`},
{value:18,text:`FiberScarf`},
{value:19,text:`Ragger2`},
{value:20,text:`BrokenSwd`},
{value:21,text:`PuppetScarf`},
{value:22,text:`FreezeRing`}
];

var armorCh1 = [
{value:0, text:`Empty`},
{value:1, text:`Amber Card`},
{value:2, text:`Dice Brace`},
{value:3, text:`Pink Ribbon`},
{value:4, text:`White Ribbon`},
{value:5, text:`IronShackle`},
{value:6, text:`MouseToken`},
{value:7, text:`Jevilstail`}
];

var armor = [
{value:0, text:`Empty`},
{value:1, text:`Amber Card`},
{value:2, text:`Dice Brace`},
{value:3, text:`Pink Ribbon`},
{value:4, text:`White Ribbon`},
{value:5, text:`IronShackle`},
{value:6, text:`MouseToken`},
{value:7, text:`Jevilstail`},
{value:8, text:`Silver Card`},
{value:9, text:`TwinRibbon`},
{value:10, text:`GlowWrist`},
{value:11, text:`ChainMail`},
{value:12, text:`B.ShotBowtie`},
{value:13, text:`SpikeBand`},
{value:14, text:`Silver Watch`},
{value:15, text:`TensionBow`},
{value:16, text:`Mannequin`},
{value:17, text:`DarkGoldBand`},
{value:18, text:`SkyMantle`},
{value:19, text:`SpikeShackle`},
{value:20, text:`FrayedBowtie`},
{value:21, text:`Dealmaker`},
{value:22, text:`RoyalPin`}
];


var itemsCh1 = [
{value:0, text:`Empty`},
{value:1, text:`Dark Candy`},
{value:2, text:`ReviveMint`},
{value:3, text:`Glowshard`},
{value:4, text:`Manual`},
{value:5, text:`BrokenCake`},
{value:6, text:`TopCake`},
{value:7, text:`SpinCake`},
{value:8, text:`Darkburger`},
{value:9, text:`LancerCookie`},
{value:10, text:`GigaSalad`},
{value:11, text:`Clubswich`},
{value:12, text:`HeartsDonut`},
{value:13, text:`ChocDiamond`},
{value:14, text:`FavSandwich`},
{value:15, text:`RouxlsRoux`}
];


var items = [
{value:0, text:`Empty`},
{value:1, text:`Dark Candy`},
{value:2, text:`ReviveMint`},
{value:3, text:`Glowshard`},
{value:4, text:`Manual`},
{value:5, text:`BrokenCake`},
{value:6, text:`TopCake`},
{value:7, text:`SpinCake`},
{value:8, text:`Darkburger`},
{value:9, text:`LancerCookie`},
{value:10, text:`GigaSalad`},
{value:11, text:`Clubswich`},
{value:12, text:`HeartsDonut`},
{value:13, text:`ChocDiamond`},
{value:14, text:`FavSandwich`},
{value:15, text:`RouxlsRoux`},
{value:16, text:`CD Bagel`},
{value:17, text:`Mannequin`},
{value:18, text:`Kris Tea`},
{value:19, text:`Noelle Tea`},
{value:20, text:`Ralsei Tea`},
{value:21, text:`Susie Tea`},
{value:22, text:`DD-Burger`},
{value:23, text:`LightCandy`},
{value:24, text:`ButJuice`},
{value:25, text:`SpagettiCode`},
{value:26, text:`JavaCookie`},
{value:27, text:`TensionBit`},
{value:28, text:`TensionGem`},
{value:29, text:`TensionMax`},
{value:30, text:`ReviveDust`},
{value:31, text:`ReviveBrite`},
{value:32, text:`S.POISON`},
{value:33, text:`DogDollar`}
];


var key_itemsCh1 = [
{value:0, text:`Empty`},
{value:1, text:`Cell Phone`},
{value:2, text:`Egg`},
{value:3, text:`BrokenCake`},
{value:4, text:`Broken Key A`},
{value:5, text:`Door Key`},
{value:6, text:`Broken Key B`},
{value:7, text:`Broken Key C`}
];

var key_items = [
{value:0, text:`Empty`},
{value:1, text:`Cell Phone`},
{value:2, text:`Egg`},
{value:3, text:`BrokenCake`},
{value:4, text:`Broken Key A`},
{value:5, text:`Door Key`},
{value:6, text:`Broken Key B`},
{value:7, text:`Broken Key C`},
{value:8, text:`Lancer`},
{value:9, text:`Rouxls Kaard`},
{value:10, text:`EmptyDisk`},
{value:11, text:`LoadedDisk`},
{value:12, text:`KeyGen`},
{value:13, text:`ShadowCrystal`},
{value:14, text:`Starwalker`},
{value:15, text:`PureCrystal`}
];

var spellsCh1 = [
{value:0, text:`Empty`},
{value:1, text:`Rude Sword`},
{value:2, text:`Heal Prayer`},
{value:3, text:`Pacify`},
{value:4, text:`Rude Buster`},
{value:5, text:`Red Buster`},
{value:6, text:`Duel Heal`},
{value:7, text:`ACT`}
];

var spells = [
{value:0, text:`Empty`},
{value:1, text:`Rude Sword`},
{value:2, text:`Heal Prayer`},
{value:3, text:`Pacify`},
{value:4, text:`Rude Buster`},
{value:5, text:`Red Buster`},
{value:6, text:`Duel Heal`},
{value:7, text:`ACT`},
{value:8, text:`SleepMist`},
{value:9, text:`IceShock`},
{value:10, text:`SnowGrave`},
{value:11, text:`UltimatHeal`}
];

var lightworld_itemsCh1 = [
{value:0, text:`Empty`},
{value:1, text:`Hot Chocolate`},
{value:2, text:`Pencil`},
{value:3, text:`Bandage`},
{value:4, text:`Bouquet`},
{value:5, text:`Ball of Junk`},
{value:6, text:`Halloween Pencil`},
{value:7, text:`Lucky Pencil`},
{value:8, text:`Egg`},
{value:11, text:`Glass`},
]

var lightworld_items = [
{value:0, text:`Empty`},
{value:1, text:`Hot Chocolate`},
{value:2, text:`Pencil`},
{value:3, text:`Bandage`},
{value:4, text:`Bouquet`},
{value:5, text:`Ball of Junk`},
{value:6, text:`Halloween Pencil`},
{value:7, text:`Lucky Pencil`},
{value:8, text:`Egg`},
{value:9, text:`Cards`},
{value:10, text:`Box of Heart Candy`},
{value:11, text:`Glass`},
{value:12, text:`Eraser`},
{value:13, text:`Mech. Pencil`},
{value:14, text:`Wristwatch`}
]

var lightworld_armorCh1 = [
{value:0, text:`Empty`},
{value:3, text:`Bandage`},
]

var lightworld_armor = [
{value:0, text:`Empty`},
{value:3, text:`Bandage`},
{value:14, text:`Wristwatch`}
]

var lightworld_weaponsCh1 = [
{value:0, text:`Empty`},
{value:2, text:`Pencil`},
{value:6, text:`Halloween Pencil`},
{value:7, text:`Lucky Pencil`}
]

var lightworld_weapons = [
{value:0, text:`Empty`},
{value:2, text:`Pencil`},
{value:6, text:`Halloween Pencil`},
{value:7, text:`Lucky Pencil`},
{value:12, text:`Eraser`}
]

var phone_numbers = [
{value:0, text:`Empty`},
{value:201, text:`Call Home`},
{value:202, text:`Sans's Number`}
]

var party_members = [
{value:0, text:`Empty`},
{value:1, text:`Kris`},
{value:2, text:`Susie`},
{value:3, text:`Ralsei`},
{value:4, text:`Noelle`}
]



var recruits = [
{value:0, text:"Known Quantity 0"},
{value:1, text:"Known Quantity 1"},
{value:2, text:"Known Quantity 2"},
{value:3, text:"Known Quantity 3"},
{value:4, text:"Known Quantity 4"},
{value:5, text:"Rudinn"},
{value:6, text:"Hathy"},
{value:7, text:"Known Quantity 7"},
{value:8, text:"Known Quantity 8"},
{value:9, text:"Known Quantity 9"},
{value:10, text:"Known Quantity 10"},
{value:11, text:"Ponman"},
{value:12, text:"Known Quantity 12"},
{value:13, text:"Rabbick"},
{value:14, text:"Bloxer"},
{value:15, text:"Jigsawry"},
{value:16, text:"Known Quantity 16"},
{value:17, text:"Known Quantity 17"},
{value:18, text:"Known Quantity 18"},
{value:19, text:"Known Quantity 19"},
{value:20, text:"JEVIL"},
{value:21, text:"Known Quantity 21"},
{value:22, text:"Rudinn Ranger"},
{value:23, text:"Head Hathy"},
{value:24, text:"Known Quantity 24"},
{value:25, text:"Known Quantity 25"},
{value:26, text:"Known Quantity 26"},
{value:27, text:"Known Quantity 27"},
{value:28, text:"Known Quantity 28"},
{value:29, text:"Known Quantity 29"},
{value:30, text:"Ambyu-Lance"},
{value:31, text:"Poppup"},
{value:32, text:"Tasque"},
{value:33, text:"Werewire"},
{value:34, text:"Maus"},
{value:35, text:"Virovirokun"},
{value:36, text:"Swatchling"},
{value:37, text:"Known Quantity 37"},
{value:38, text:"Known Quantity 38"},
{value:39, text:"Known Quantity 39"},
{value:40, text:"Werewerewire"},
{value:41, text:"Known Quantity 41"},
{value:42, text:"Tasque Manager"},
{value:43, text:"Known Quantity 43"},
{value:44, text:"Mauswheel"},
{value:45, text:"Known Quantity 45"},
{value:46, text:"Known Quantity 46"},
{value:47, text:"Known Quantity 47"},
{value:48, text:"Known Quantity 48"},
{value:49, text:"Known Quantity 49"}
]

var unused_recruits = [
  0,1,2,3,4,7,8,9,10,12,16,17,18,19,20,21,24,25,26,27,28,29,37,38,39,41,43,45,46,47,48,49
];

var thrasher_head_parts  = [
  {value:0,text:`LASER`},
  {value:1,text:`SWORD`},
  {value:2,text:`FLAME`},
  {value:3,text:`DUCK`},
];

var thrasher_body_parts  = [
  {value:0,text:`PLAIN`},
  {value:1,text:`WHEEL`},
  {value:2,text:`TANK`},
  {value:3,text:`DUCK`},
];


var thrasher_feet_parts  = [
  {value:0,text:`SNEAK`},
  {value:1,text:`A.WHL`},
  {value:2,text:`TREAD`},
  {value:3,text:`DUCK`},
];

var goner_food = [
  {value:0,text:`SWEET`},
  {value:1,text:`SOFT`},
  {value:2,text:`SOUR`},
  {value:3,text:`SALTY`},
  {value:4,text:`PAIN`},
  {value:5,text:`COLD`}
]

var goner_blood = [

    {value:0,text:`A`},
    {value:1,text:`AB`},
    {value:2,text:`B`},
    {value:3,text:`C`},
    {value:4,text:`D`}
]

var goner_color = [

    {value:0,text:`RED`},
    {value:1,text:`BLUE`},
    {value:2,text:`GREEN`},
    {value:3,text:`CYAN`}
]

var goner_feel = [

    {value:0,text:`LOVE`},
    {value:1,text:`HOPE`},
    {value:2,text:`DISGUST`},
    {value:3,text:`FEAR`}
]

var goner_gift = [

    {value:1,text:`KINDNESS`},
    {value:0,text:`MIND`},
    {value:-1,text:`AMBITION`},
    {value:-2,text:`BRAVERY`},
    {value:-3,text:`VOICE`}
]
