var rooms = [
  {value:40014,text:`Kris's Room`},
  {value:40023,text:`Hometown`},
  {value:40048,text:`Noelle's House`},
  {value:40064,text:`Castle Town`},
  {value:40065,text:`My Castle Town`},
  {value:40108,text:`Dark Sanctuary - Atrium`},
  {value:40115,text:`Dark Sanctuary - Study`},
  {value:40177,text:`Dark Sanctuary - Lower Left`},
  {value:40219,text:`Dark Sanctuary - Small Piano`},
  {value:40220,text:`Dark Sanctuary - Library`},
  {value:40228,text:`Dark Sanctuary - Lower Right`},
  {value:40248,text:`2nd Sanctuary - Atrium`},
  {value:40252,text:`2nd Sanctuary - Floor`},
  {value:40258,text:`2nd Sanctuary - Study`},
  {value:40271,text:`3rd Sanctuary`},
  {value:40278,text:`3rd Sanctuary - Stairs`},
  {value:40281,text:`3rd Sanctuary - Last Chamber`},
  {value:40306,text:`2nd Sanctuary - Study`},
  {value:40322,text:`MIKE ZONE`}
];


var rooms_all = [
  {value: 40014, text: `room_krisroom`},
  {value: 40015, text: `room_krishallway`},
  {value: 40016, text: `room_torroom`},
  {value: 40017, text: `room_torhouse`},
  {value: 40018, text: `room_torbathroom`},
  {value: 40019, text: `room_town_krisyard`},
  {value: 40020, text: `room_town_northwest`},
  {value: 40021, text: `room_town_north`},
  {value: 40022, text: `room_beach`},
  {value: 40023, text: `room_town_mid`},
  {value: 40024, text: `room_town_apartments`},
  {value: 40025, text: `room_town_south`},
  {value: 40026, text: `room_town_school`},
  {value: 40027, text: `room_town_church`},
  {value: 40028, text: `room_graveyard`},
  {value: 40029, text: `room_town_shelter`},
  {value: 40030, text: `room_hospital_lobby`},
  {value: 40031, text: `room_hospital_hallway`},
  {value: 40032, text: `room_hospital_rudy`},
  {value: 40033, text: `room_hospital_room2`},
  {value: 40034, text: `room_diner`},
  {value: 40035, text: `room_townhall`},
  {value: 40036, text: `room_flowershop_1f`},
  {value: 40037, text: `room_flowershop_2f`},
  {value: 40038, text: `room_library`},
  {value: 40039, text: `room_alphysalley`},
  {value: 40040, text: `room_lw_computer_lab`},
  {value: 40041, text: `room_lw_library_upstairs`},
  {value: 40042, text: `room_lw_police`},
  {value: 40043, text: `room_lw_conbini`},
  {value: 40044, text: `room_lw_icee_pizza`},
  {value: 40045, text: `room_lw_church_entrance`},
  {value: 40046, text: `room_lw_church_main`},
  {value: 40047, text: `room_lw_noellehouse_main`},
  {value: 40048, text: `room_lw_noellehouse_kitchen`},
  {value: 40049, text: `room_lw_noellehouse_bathroom`},
  {value: 40050, text: `room_lw_noellehouse_keyroom`},
  {value: 40051, text: `room_lw_noellehouse_noelle`},
  {value: 40052, text: `room_lw_noellehouse_dess`},
  {value: 40053, text: `room_lw_noellehouse_closet`},
  {value: 40054, text: `room_torielclass`},
  {value: 40055, text: `room_schoollobby`},
  {value: 40056, text: `room_alphysclass`},
  {value: 40057, text: `room_schooldoor`},
  {value: 40058, text: `room_insidecloset`},
  {value: 40059, text: `room_school_unusedroom`},
  {value: 40060, text: `room_castle_tutorial`},
  {value: 40061, text: `room_dw_castle_east_door`},
  {value: 40062, text: `room_dw_castle_west_cliff`},
  {value: 40063, text: `room_dw_castle_area_1`},
  {value: 40064, text: `room_dw_castle_town`},
  {value: 40065, text: `room_dw_ralsei_castle_front`},
  {value: 40066, text: `room_dw_castle_restaurant`},
  {value: 40067, text: `room_dw_castle_cafe`},
  {value: 40068, text: `room_dw_castle_dojo`},
  {value: 40069, text: `room_dw_ralsei_castle_1f`},
  {value: 40070, text: `room_dw_ralsei_castle_2f`},
  {value: 40071, text: `room_dw_castle_dungeon`},
  {value: 40072, text: `room_dw_castle_rooms_kris`},
  {value: 40073, text: `room_dw_castle_rooms_susie`},
  {value: 40083, text: `PLACE_MENU`},
  {value: 40088, text: `room_cc_lancer`},
  {value: 40089, text: `room_cc_clover`},
  {value: 40090, text: `room_cc_fountain`},
  {value: 40101, text: `room_dw_church_slidingbookshelf`},
  {value: 40104, text: `room_dw_church_bellplay`},
  {value: 40105, text: `room_intro_ch4`},
  {value: 40106, text: `room_dw_church_candlelighting`},
  {value: 40107, text: `room_town_noellehouse`},
  {value: 40108, text: `room_dw_church_intro1`},
  {value: 40109, text: `room_dw_church_intro3`},
  {value: 40110, text: `room_dw_church_intro_guei`},
  {value: 40113, text: `room_dw_church_lantern_hallway`},
  {value: 40115, text: `room_dw_church_gersonstudy`},
  {value: 40116, text: `room_dw_church_stairs_west_bell`},
  {value: 40117, text: `room_dw_church_librarybookenemy`},
  {value: 40118, text: `room_dw_church_bookshelfpuzzle1`},
  {value: 40119, text: `room_dw_church_bookshelfpuzzle2`},
  {value: 40120, text: `room_dw_church_worshiproom`},
  {value: 40121, text: `room_dw_church_swingingbell`},
  {value: 40122, text: `room_dw_church_tallbookcases`},
  {value: 40123, text: `room_dw_church_lantern2`},
  {value: 40124, text: `room_dw_church_smallbells`},
  {value: 40125, text: `room_dw_church_claw`},
  {value: 40126, text: `room_dw_church_shelfclimb1`},
  {value: 40127, text: `room_dw_church_statueclimb`},
  {value: 40128, text: `room_dw_church_offering`},
  {value: 40129, text: `room_dw_church_npcroom_shelfclimb`},
  {value: 40130, text: `room_dw_church_stairs_stainedglass`},
  {value: 40131, text: `room_dw_church_bellsareawest`},
  {value: 40132, text: `room_dw_church_stairs_topright`},
  {value: 40133, text: `room_dw_church_poolsroom1`},
  {value: 40134, text: `room_dw_church_candlesroom1`},
  {value: 40135, text: `room_dw_church_solowaterfall`},
  {value: 40136, text: `room_dw_church_statueroom`},
  {value: 40137, text: `room_dw_church_poolsroom2`},
  {value: 40138, text: `room_dw_church_shelfclimb2`},
  {value: 40139, text: `room_dw_church_statueclimb_npcroom`},
  {value: 40140, text: `room_dw_church_bellhall_west`},
  {value: 40141, text: `room_dw_church_fountainconnection`},
  {value: 40142, text: `room_dw_church_stainedglasspreview`},
  {value: 40143, text: `room_dw_church_stairs_topleft`},
  {value: 40144, text: `room_dw_church_npcroom_pools1`},
  {value: 40145, text: `room_dw_church_poolsroom1_east`},
  {value: 40146, text: `room_dw_church_minorlegend`},
  {value: 40147, text: `room_dw_church_bookenemywest`},
  {value: 40148, text: `room_dw_church_poolsroom2south`},
  {value: 40149, text: `room_lw_church_office`},
  {value: 40150, text: `room_dw_church_bellhall_east`},
  {value: 40151, text: `room_dw_church_bellhall_central`},
  {value: 40154, text: `room_dw_ralsei_castle_3f`},
  {value: 40155, text: `room_dw_castle_rooms_ralsei`},
  {value: 40156, text: `room_dw_rotating_tower`},
  {value: 40159, text: `room_krisroom_dark`},
  {value: 40162, text: `room_lw_noellehouse_vents_west`},
  {value: 40166, text: `room_town_krisyard_dark`},
  {value: 40167, text: `room_dw_castle_rooms_queen`},
  {value: 40168, text: `room_dw_castle_rooms_tenna`},
  {value: 40171, text: `room_dw_church_ripplepuzzle`},
  {value: 40173, text: `room_dw_church_glass`},
  {value: 40174, text: `room_dw_church_staircase`},
  {value: 40175, text: `room_dw_church_bellhall_bookroom`},
  {value: 40176, text: `room_dw_church_bookcase`},
  {value: 40177, text: `room_dw_church_savepoint`},
  {value: 40178, text: `room_dw_church_dark_fire_puzzle`},
  {value: 40179, text: `room_dw_church_turtles`},
  {value: 40180, text: `room_dw_church_guei`},
  {value: 40181, text: `room_dw_church_jackenstein`},
  {value: 40182, text: `room_dw_church_bellhall_curtain`},
  {value: 40184, text: `room_dw_church_dogclimb`},
  {value: 40185, text: `room_dw_church_arena`},
  {value: 40192, text: `room_dw_churchb_nongerson_post`},
  {value: 40193, text: `room_lw_noellehouse_vents_north`},
  {value: 40194, text: `room_lw_noellehouse_vents_east`},
  {value: 40195, text: `room_lw_noellehouse_vents_south`},
  {value: 40205, text: `room_dw_church_climbtut`},
  {value: 40206, text: `room_dw_church_fastwater`},
  {value: 40207, text: `room_dw_church_crumbletower`},
  {value: 40208, text: `room_dw_church_tower1`},
  {value: 40209, text: `room_lw_church_choir`},
  {value: 40210, text: `room_dw_church_bellclimb`},
  {value: 40211, text: `room_dw_church_shiftclimb`},
  {value: 40212, text: `room_dw_church_intropiano`},
  {value: 40213, text: `room_dw_church_intro_gerson`},
  {value: 40214, text: `room_dw_church_pianopiece_left`},
  {value: 40215, text: `room_dw_church_northprophecies`},
  {value: 40216, text: `room_dw_church_darkmaze`},
  {value: 40217, text: `room_dw_church_quicktest`},
  {value: 40218, text: `room_dw_church_pianopiece_right`},
  {value: 40219, text: `room_dw_church_pianopuzzle`},
  {value: 40220, text: `room_dw_church_nwconnect`},
  {value: 40221, text: `room_dw_church_rightconnect`},
  {value: 40222, text: `room_dw_church_stairspreview`},
  {value: 40223, text: `room_dw_church_trueclimbadventure`},
  {value: 40224, text: `room_dw_church_organpuzzle`},
  {value: 40225, text: `room_dw_church_mizzleencounter`},
  {value: 40226, text: `room_dw_church_sideclimb`},
  {value: 40227, text: `room_dw_church_secretpiano`},
  {value: 40228, text: `room_dw_church_ripplepuzzle_postgers`},
  {value: 40229, text: `room_dw_church_tallbookcases_backup`},
  {value: 40230, text: `room_dw_church_fountain`},
  {value: 40231, text: `room_dw_church_b_intro`},
  {value: 40232, text: `room_dw_churchc_final_prophecy`},
  {value: 40233, text: `room_dw_church_bookshelfpuzzle`},
  {value: 40234, text: `room_lw_noellehouse_basement`},
  {value: 40235, text: `room_dw_church_biblioxencounter`},
  {value: 40236, text: `room_dw_church_darkclimb`},
  {value: 40237, text: `room_dw_church_moneyfountain`},
  {value: 40239, text: `room_dw_church_pianopiece_left_b`},
  {value: 40240, text: `room_dw_church_pianopiece_rightprophecy`},
  {value: 40242, text: `room_dw_church_shadowgerson`},
  {value: 40243, text: `room_dw_church_holywatercooler`},
  {value: 40244, text: `room_dw_church_rippleworship`},
  {value: 40245, text: `room_dw_church_waterfallroom`},
  {value: 40246, text: `room_dw_church_waterfalltearoom`},
  {value: 40247, text: `room_dw_castle_rooms_kris_susie`},
  {value: 40248, text: `room_dw_churchb_staircaseintro`},
  {value: 40249, text: `room_dw_churchb_prophecyencounter`},
  {value: 40250, text: `room_dw_churchb_worshiproom`},
  {value: 40251, text: `room_dw_churchb_libraryconnector`},
  {value: 40252, text: `room_dw_churchb_savepoint`},
  {value: 40253, text: `room_dw_churchb_rotatingtower`},
  {value: 40254, text: `room_dw_churchb_bellroom`},
  {value: 40255, text: `room_dw_churchb_escherstaircase`},
  {value: 40256, text: `room_dw_churchb_prophecymaze`},
  {value: 40257, text: `room_dw_churchb_rotatingtower2`},
  {value: 40258, text: `room_dw_churchb_gersonstudy`},
  {value: 40259, text: `room_dw_churchb_gersonchase`},
  {value: 40260, text: `room_dw_churchb_extinguisher`},
  {value: 40261, text: `room_dw_church_knightclimb`},
  {value: 40262, text: `room_dw_church_knightclimb_post`},
  {value: 40263, text: `room_dw_rhythm`},
  {value: 40264, text: `room_dw_rhythm_countdown`},
  {value: 40265, text: `room_dw_rhythm_empty`},
  {value: 40266, text: `room_rhythmgame_editor`},
  {value: 40267, text: `room_dw_churchb_ripple1`},
  {value: 40268, text: `room_dw_churchb_ripplepost`},
  {value: 40269, text: `room_dw_churchb_library_alternate`},
  {value: 40270, text: `room_dw_churchb_moneyfountain`},
  {value: 40271, text: `room_dw_churchc_superprophecies`},
  {value: 40272, text: `room_dw_churchc_encounter1`},
  {value: 40273, text: `room_dw_churchc_slidingpiano`},
  {value: 40274, text: `room_dw_churchc_ripplesneak_poc`},
  {value: 40275, text: `room_dw_churchc_encounter2`},
  {value: 40276, text: `room_dw_churchc_finalclimb`},
  {value: 40277, text: `room_dw_churchc_angelprophecy_encounter`},
  {value: 40278, text: `room_dw_churchc_savepoint`},
  {value: 40279, text: `room_dw_churchc_darkswords`},
  {value: 40280, text: `room_dw_churchc_pretitan`},
  {value: 40281, text: `room_dw_churchc_prepretitan`},
  {value: 40282, text: `room_dw_churchc_titandefeated`},
  {value: 40283, text: `room_dw_churchb_fountain`},
  {value: 40284, text: `room_dw_church_ripseq1`},
  {value: 40285, text: `room_dw_church_ripseq2`},
  {value: 40286, text: `room_dw_churchc_titanclimb1`},
  {value: 40287, text: `room_dw_churchc_titanclimb2`},
  {value: 40291, text: `room_lw_noellehouse_north`},
  {value: 40292, text: `room_lw_noellehouse_vents_north_west`},
  {value: 40296, text: `room_dw_churchb_fireplace`},
  {value: 40297, text: `room_dw_churchb_nongerson`},
  {value: 40298, text: `room_dw_churchb_library`},
  {value: 40299, text: `room_dw_castle_tv_rhythm`},
  {value: 40300, text: `room_dw_castle_tv`},
  {value: 40301, text: `room_dw_churchb_windows`},
  {value: 40302, text: `room_dw_churchb_bookshelf`},
  {value: 40303, text: `room_dw_churchb_man`},
  {value: 40304, text: `room_dw_churchb_gallery`},
  {value: 40305, text: `room_dw_churchb_rotatingtower_old`},
  {value: 40306, text: `room_dw_churchb_darkclimb`},
  {value: 40307, text: `room_dw_churchc_titanclimb1_post`},
  {value: 40308, text: `room_dw_churchc_titanclimb2_post`},
  {value: 40309, text: `room_dw_churchb_darkclimb_scene`},
  {value: 40310, text: `room_dw_churchc_dodge`},
  {value: 40311, text: `room_dw_churchc_insidetitan`},
  {value: 40313, text: `room_dw_churchc_prophecies`},
  {value: 40314, text: `room_dw_churchc_angelprophecy`},
  {value: 40315, text: `room_dw_church_bookshelfpuzzle_rev`},
  {value: 40317, text: `room_dw_churchc_treasurechest`},
  {value: 40321, text: `room_dw_castle_tv_zone_1`},
  {value: 40322, text: `room_dw_castle_tv_zone_2`},
  {value: 40323, text: `room_dw_castle_tv_zone_3`},
  {value: 40324, text: `room_dw_castle_tv_zone_battle`},
  {value: 40325, text: `room_dw_castle_tv_zone_minigame`}
];



var weapons = [
{value:0,text:`(Nothing)`},
{value:1,text:`Wood Blade`},
{value:2,text:`Mane Ax`},
{value:3,text:`Red Scarf`},
{value:4,text:`EverybodyWeapon`},
{value:5,text:`Spookysword`},
{value:6,text:`Brave Ax`},
{value:7,text:`Devilsknife`},
{value:8,text:`Trefoil`},
{value:9,text:`Ragger`},
{value:10,text:`DaintyScarf`},
{value:11,text:`TwistedSwd`},
{value:12,text:`SnowRing`},
{value:13,text:`ThornRing`},
{value:14,text:`BounceBlade`},
{value:15,text:`CheerScarf`},
{value:16,text:`MechaSaber`},
{value:17,text:`AutoAxe`},
{value:18,text:`FiberScarf`},
{value:19,text:`Ragger2`},
{value:20,text:`BrokenSwd`},
{value:21,text:`PuppetScarf`},
{value:22,text:`FreezeRing`},
{value:23,text:`Saber10`},
{value:24,text:`ToxicAxe`},
{value:25,text:`FlexScarf`},
{value:26,text:`BlackShard`},
{value:50,text:`JingleBlade`},
{value:51,text:`ScarfMark`},
{value:52,text:`JusticeAxe`},
{value:53,text:`Winglade`},
{value:54,text:`AbsorbAx`}
];

var armor = [
{value:0, text:`Empty`},
{value:1, text:`Amber Card`},
{value:2, text:`Dice Brace`},
{value:3, text:`Pink Ribbon`},
{value:4, text:`White Ribbon`},
{value:5, text:`IronShackle`},
{value:6, text:`MouseToken`},
{value:7, text:`Jevilstail`},
{value:8, text:`Silver Card`},
{value:9, text:`TwinRibbon`},
{value:10, text:`GlowWrist`},
{value:11, text:`ChainMail`},
{value:12, text:`B.ShotBowtie`},
{value:13, text:`SpikeBand`},
{value:14, text:`Silver Watch`},
{value:15, text:`TensionBow`},
{value:16, text:`Mannequin`},
{value:17, text:`DarkGoldBand`},
{value:18, text:`SkyMantle`},
{value:19, text:`SpikeShackle`},
{value:20, text:`FrayedBowtie`},
{value:21, text:`Dealmaker`},
{value:22, text:`RoyalPin`},
{value:23, text:`ShadowMantle`},
{value:24, text:`LodeStone`},
{value:25, text:`GingerGuard`},
{value:26, text:`BlueRibbon`},
{value:27, text:`TennaTie`},
{value:50, text:`Waterguard`},
{value:51, text:`MysticBand`},
{value:52, text:`PowerBand`},
{value:53, text:`PrincessRBN`},
{value:54, text:`GoldWidow`}
];


var items = [
{value:0, text:`Empty`},
{value:1, text:`Dark Candy`},
{value:2, text:`ReviveMint`},
{value:3, text:`Glowshard`},
{value:4, text:`Manual`},
{value:5, text:`BrokenCake`},
{value:6, text:`TopCake`},
{value:7, text:`SpinCake`},
{value:8, text:`Darkburger`},
{value:9, text:`LancerCookie`},
{value:10, text:`GigaSalad`},
{value:11, text:`Clubswich`},
{value:12, text:`HeartsDonut`},
{value:13, text:`ChocDiamond`},
{value:14, text:`FavSandwich`},
{value:15, text:`RouxlsRoux`},
{value:16, text:`CD Bagel`},
{value:17, text:`Mannequin`},
{value:18, text:`Kris Tea`},
{value:19, text:`Noelle Tea`},
{value:20, text:`Ralsei Tea`},
{value:21, text:`Susie Tea`},
{value:22, text:`DD-Burger`},
{value:23, text:`LightCandy`},
{value:24, text:`ButJuice`},
{value:25, text:`SpagettiCode`},
{value:26, text:`JavaCookie`},
{value:27, text:`TensionBit`},
{value:28, text:`TensionGem`},
{value:29, text:`TensionMax`},
{value:30, text:`ReviveDust`},
{value:31, text:`ReviveBrite`},
{value:32, text:`S.POISON`},
{value:33, text:`DogDollar`},
{value:34, text:`TVDinner`},
{value:35, text:`Pipis`},
{value:36, text:`FlatSoda`},
{value:37, text:`TVSlop`},
{value:38, text:`ExecBuffet`},
{value:39, text:`DeluxeDinner`},
{value:60, text:`AncientSweet`},
{value:61, text:`Rhapsotea`},
{value:62, text:`Scarlixir`},
{value:63, text:`BitterTear`}
];


var key_items = [
{value:0, text:`Empty`},
{value:1, text:`Cell Phone`},
{value:2, text:`Egg`},
{value:3, text:`BrokenCake`},
{value:4, text:`Broken Key A`},
{value:5, text:`Door Key`},
{value:6, text:`Broken Key B`},
{value:7, text:`Broken Key C`},
{value:8, text:`Lancer`},
{value:9, text:`Rouxls Kaard`},
{value:10, text:`EmptyDisk`},
{value:11, text:`LoadedDisk`},
{value:12, text:`KeyGen`},
{value:13, text:`ShadowCrystal`},
{value:14, text:`Starwalker`},
{value:15, text:`PureCrystal`},
{value:16, text:`OddController`},
{value:17, text:`BackstagePass`},
{value:18, text:`TripTicket`},
{value:19, text:`LancerCon`},
{value:30, text:`SheetMusic`},
{value:31, text:`ClaimbClaws`}
];


var spells = [
{value:0, text:`Empty`},
{value:1, text:`Rude Sword`},
{value:2, text:`Heal Prayer`},
{value:3, text:`Pacify`},
{value:4, text:`Rude Buster`},
{value:5, text:`Red Buster`},
{value:6, text:`Duel Heal`},
{value:7, text:`ACT`},
{value:8, text:`SleepMist`},
{value:9, text:`IceShock`},
{value:10, text:`SnowGrave`},
{value:11, text:`OKHeal`}
];


var lightworld_items = [
{value:0, text:`Empty`},
{value:1, text:`Hot Chocolate`},
{value:2, text:`Pencil`},
{value:3, text:`Bandage`},
{value:4, text:`Bouquet`},
{value:5, text:`Ball of Junk`},
{value:6, text:`Halloween Pencil`},
{value:7, text:`Lucky Pencil`},
{value:8, text:`Egg`},
{value:9, text:`Cards`},
{value:10, text:`Box of Heart Candy`},
{value:11, text:`Glass`},
{value:12, text:`Eraser`},
{value:13, text:`Mech. Pencil`},
{value:14, text:`Wristwatch`},
{value:15, text:`Holiday Pencil`},
{value:16, text:`CactusNeedle`},
{value:17, text:`BlackShard`},
{value:18, text:`QuillPen`}
]


var lightworld_armor = [
{value:0, text:`Empty`},
{value:3, text:`Bandage`},
{value:14, text:`Wristwatch`}
]


var lightworld_weapons = [
{value:0, text:`Empty`},
{value:2, text:`Pencil`},
{value:6, text:`Halloween Pencil`},
{value:7, text:`Lucky Pencil`},
{value:12, text:`Eraser`},
{value:15, text:`CactusNeedle`}
]

var phone_numbers = [
{value:0, text:`Empty`},
{value:201, text:`Call Home`},
{value:202, text:`Sans's Number`}
]

var party_members = [
{value:0, text:`Empty`},
{value:1, text:`Kris`},
{value:2, text:`Susie`},
{value:3, text:`Ralsei`},
{value:4, text:`Noelle`}
]



var recruits = [
{value:0, text:"Known Quantity 0"},
{value:1, text:"Known Quantity 1"},
{value:2, text:"Known Quantity 2"},
{value:3, text:"Known Quantity 3"},
{value:4, text:"Known Quantity 4"},
{value:5, text:"Rudinn"},
{value:6, text:"Hathy"},
{value:7, text:"Known Quantity 7"},
{value:8, text:"Known Quantity 8"},
{value:9, text:"Known Quantity 9"},
{value:10, text:"Known Quantity 10"},
{value:11, text:"Ponman"},
{value:12, text:"Known Quantity 12"},
{value:13, text:"Rabbick"},
{value:14, text:"Bloxer"},
{value:15, text:"Jigsawry"},
{value:16, text:"Known Quantity 16"},
{value:17, text:"Known Quantity 17"},
{value:18, text:"Known Quantity 18"},
{value:19, text:"Known Quantity 19"},
{value:20, text:"JEVIL"},
{value:21, text:"Known Quantity 21"},
{value:22, text:"Rudinn Ranger"},
{value:23, text:"Head Hathy"},
{value:24, text:"Known Quantity 24"},
{value:25, text:"Known Quantity 25"},
{value:26, text:"Known Quantity 26"},
{value:27, text:"Known Quantity 27"},
{value:28, text:"Known Quantity 28"},
{value:29, text:"Known Quantity 29"},
{value:30, text:"Ambyu-Lance"},
{value:31, text:"Poppup"},
{value:32, text:"Tasque"},
{value:33, text:"Werewire"},
{value:34, text:"Maus"},
{value:35, text:"Virovirokun"},
{value:36, text:"Swatchling"},
{value:37, text:"Known Quantity 37"},
{value:38, text:"Known Quantity 38"},
{value:39, text:"Known Quantity 39"},
{value:40, text:"Werewerewire"},
{value:41, text:"Known Quantity 41"},
{value:42, text:"Tasque Manager"},
{value:43, text:"Known Quantity 43"},
{value:44, text:"Mauswheel"},
{value:45, text:"Known Quantity 45"},
{value:46, text:"Known Quantity 46"},
{value:47, text:"Known Quantity 47"},
{value:48, text:"Known Quantity 48"},
{value:49, text:"Known Quantity 49"},
{value:50, text:"Known Quantity 50"},
{value:51, text:"Known Quantity 51"},
{value:52, text:"Known Quantity 52"},
{value:53, text:"Known Quantity 53"},
{value:54, text:"Shadowguy"},
{value:55, text:"Shuttah"},
{value:56, text:"Zapper"},
{value:57, text:"Ribbick"},
{value:58, text:"Watercooler"},
{value:59, text:"Pippins"},
{value:60, text:"Elnina"},
{value:61, text:"Lanino"},
{value:62, text:"Guei"},
{value:63, text:"Balthizard"},
{value:64, text:"Bibliox"},
{value:65, text:"Mizzle"},
{value:66, text:"Wicabel"},
{value:67, text:"Winglade"},
{value:68, text:"Organikk"},
{value:69, text:"Miss Mizzle"},
{value:70, text:"Known Quantity 70"},
{value:71, text:"Known Quantity 71"},
{value:72, text:"Known Quantity 72"},
{value:73, text:"Known Quantity 73"},
{value:74, text:"Known Quantity 74"},
{value:75, text:"Known Quantity 75"},
{value:76, text:"Known Quantity 76"},
{value:77, text:"Known Quantity 77"},
{value:78, text:"Known Quantity 78"},
{value:79, text:"Known Quantity 79"}
]

var unused_recruits = [
  0,1,2,3,4,7,8,9,10,12,16,17,18,19,20,21,24,25,26,27,28,29,37,38,39,41,43,45,46,47,48,49,
  50,51,52,53,70,71,72,73,74,75,76,77,78,79
];

var thrasher_head_parts  = [
  {value:0,text:`LASER`},
  {value:1,text:`SWORD`},
  {value:2,text:`FLAME`},
  {value:3,text:`DUCK`},
];

var thrasher_body_parts  = [
  {value:0,text:`PLAIN`},
  {value:1,text:`WHEEL`},
  {value:2,text:`TANK`},
  {value:3,text:`DUCK`},
];


var thrasher_feet_parts  = [
  {value:0,text:`SNEAK`},
  {value:1,text:`A.WHL`},
  {value:2,text:`TREAD`},
  {value:3,text:`DUCK`},
];

var goner_food = [
  {value:0,text:`SWEET`},
  {value:1,text:`SOFT`},
  {value:2,text:`SOUR`},
  {value:3,text:`SALTY`},
  {value:4,text:`PAIN`},
  {value:5,text:`COLD`}
]

var goner_blood = [

    {value:0,text:`A`},
    {value:1,text:`AB`},
    {value:2,text:`B`},
    {value:3,text:`C`},
    {value:4,text:`D`}
]

var goner_color = [

    {value:0,text:`RED`},
    {value:1,text:`BLUE`},
    {value:2,text:`GREEN`},
    {value:3,text:`CYAN`}
]

var goner_feel = [

    {value:0,text:`LOVE`},
    {value:1,text:`HOPE`},
    {value:2,text:`DISGUST`},
    {value:3,text:`FEAR`}
]

var goner_gift = [

    {value:1,text:`KINDNESS`},
    {value:0,text:`MIND`},
    {value:-1,text:`AMBITION`},
    {value:-2,text:`BRAVERY`},
    {value:-3,text:`VOICE`}
]
